tap `caskroom/cask`
tap `github/bootstrap`
tap `homebrew/services`
brew `brew-cask`
brew `cmake`
brew `cscope`
brew `fish`
brew `fonttools`
brew `gdbm`
brew `gettext`
brew `git`
brew `glib`
brew `htop-osx`
brew `irssi`  
brew `libevent`
brew `libffi`
brew `libyaml`
brew `lynx`
brew `macvim`
brew `mysql`
brew `node`
brew `openssl`
brew `pkg-config`
brew `python`
brew `rbenv`
brew `readline`
brew `reattach-to-user-namespace`
brew `ruby`
brew `ruby-build`
brew `sqlite`
brew `syncthing`
brew `tmux`
brew `xz`
cask `gyazo`
cask `gyazogif`
cask `transmission`
