#!/bin/bash
set -eo pipefail
trap 'kill $pids' INT TERM

run(){
  tag=${@: -1} # Last ARGV use a 'tag'
  set -- "${@:1:$(($#-1))}" # delete the tag from the arg list

  prefix="${PWD##*/} $tag"
  size=$((24 - ${#prefix}))
  $@ > >(sed 's/^/'"$(tput setaf $(((RANDOM % 10) + 1)))"' '""$(date -u +"%H:%M:%S")""' '"$prefix"' '"$(printf "%-${size}s")"' | '"$(tput sgr0)"'/') &
  pids="$pids $(jobs -p %%)"
}

cd $HOME && run ls 'my-tag'

wait
exit 0
